ESSA E A MISTURA DA ALEMANHA COM O EGITO
TEM QUE TER CHARME PRA DANCAR BONITO
ESSE AGITO QUENTE QUE NEM AREIA NO SAARA ME QUEIMA VAI
VAMO EMBORA
ESSA E A MISTURA DA ALEMANHA
COM O EGITO
TEM QUE TER CHARME PRA DANCAR BONITO
